name: Lint

on: [push]

jobs:   
  eslint:
    runs-on: ubuntu-latest    
    steps:
       - name: Install Git
         run: |
          sudo apt-get install -y git          
       - name: ESLINT
       - uses: actions/checkout@v1
       - uses: stefanoeb/eslint-action@1.0.2
         with:
           files: src/
